### **Use of FastText : -**

In [4]:
import fasttext

### Pre trained model:-

In [5]:
model_en = fasttext.load_model("cc.en.300.bin")

In [6]:
dir(model_en)

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_labels',
 '_words',
 'f',
 'get_analogies',
 'get_dimension',
 'get_input_matrix',
 'get_input_vector',
 'get_label_id',
 'get_labels',
 'get_line',
 'get_meter',
 'get_nearest_neighbors',
 'get_output_matrix',
 'get_sentence_vector',
 'get_subword_id',
 'get_subwords',
 'get_word_id',
 'get_word_vector',
 'get_words',
 'is_quantized',
 'labels',
 'predict',
 'quantize',
 'save_model',
 'set_args',
 'set_matrices',
 'test',
 'test_label',
 'words']

In [7]:
model_en.get_nearest_neighbors("depression")

[(0.7752668857574463, 'depresssion'),
 (0.7331328988075256, 'depression.The'),
 (0.7331280708312988, 'depression-'),
 (0.7269230484962463, 'depression.This'),
 (0.725515604019165, 'depresion'),
 (0.7201564311981201, 'depression.'),
 (0.7074428200721741, 'depressio'),
 (0.7064437866210938, 'Depression'),
 (0.7063635587692261, 'depression.It'),
 (0.7004572749137878, 'depression.But')]

In [8]:
model_en.get_word_vector("bad").shape

(300,)

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("mental_heath_unbanlanced.csv")
df.sample(9)

,Unique_ID,text,status
40500,NaN,I have never laughed so hard So the other day ...,Normal
10819,12189.0,I have let it all go. I am too depressed to ge...,Depression
507,511.0,"Seriously, I've never been worried about getti...",Anxiety
8647,9412.0,I have been feeling negative and toxic. it is ...,Depression
9359,10300.0,Why do I always start feeling extremely lonely...,Suicidal
2842,2934.0,OH GOD WANT TO FOLLOW WHO ELSE FORGETS TO UNAM...,Normal
21286,25404.0,"I want someone who will be close with me, shar...",Depression
48792,NaN,i understand this is an extremely morbid title...,Depression
41585,NaN,"It never got better-They said that, if I quit ...",Suicidal

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49612 entries, 0 to 49611
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Unique_ID  40012 non-null  float64
 1   text       49612 non-null  object
 2   status     49612 non-null  object
dtypes: float64(1), object(2)
memory usage: 1.1+ MB

In [12]:
df.isnull().sum()

Unique_ID    9600
text            0
status          0
dtype: int64

In [13]:
df.text[4]

"I'm restless and restless, it's been a month now, boy. What do you mean?"

In [14]:
import re
text = "I'm restless and restless, it's been a month now, boy. What do you mean?"
clean_text = re.sub(r"[^\w\s]", "", text)
clean_text

'Im restless and restless its been a month now boy What do you mean'

In [15]:
def prepros(text):
    clean_text = re.sub(r"[^\w\s]", "", text)
    clean_text = re.sub(r"[ \n]+"," ",clean_text)
    return clean_text.strip().lower()

text = "I'm restless and restless, it's been a month now, boy. What do you mean?"
prepros(text)

'im restless and restless its been a month now boy what do you mean'

### **Build my own model: -**

In [16]:
df["prepros_text"] = df["text"].apply(lambda x : prepros(x))
df.sample(7)

,Unique_ID,text,status,prepros_text
43639,NaN,I'd probably be dead if music didnt exist idk ...,Normal,id probably be dead if music didnt exist idk j...
32834,39907.0,f and going through a really bad break up up u...,Depression,f and going through a really bad break up up u...
28013,34164.0,Light-headedness A few days ago I did a pass o...,Anxiety,lightheadedness a few days ago i did a pass ou...
37777,44989.0,http twitter com freddybust status thats right,Normal,http twitter com freddybust status thats right
37303,44513.0,sitting outside doctor s surgery so it s my tu...,Normal,sitting outside doctor s surgery so it s my tu...
5788,5999.0,"If you think about it, it's really easy to ask...",Normal,if you think about it its really easy to ask s...
30982,37588.0,@photojunkie I thought it said &quot;looking t...,Normal,photojunkie i thought it said quotlooking to g...

In [17]:
df.to_csv("test.text",columns=["prepros_text"],index=False,header=None)

### Training : -

In [18]:
my_model = fasttext.train_unsupervised("test.text")

Read 3M words
Number of words:  13555
Number of labels: 0
Progress: 100.0% words/sec/thread:  150670 lr:  0.000000 avg.loss:  2.315142 ETA:   0h 0m 0s

In [21]:
my_model.get_nearest_neighbors("cruel")

[(0.9076375365257263, 'cruelty'),
 (0.8405517935752869, 'cruelest'),
 (0.709631621837616, 'worldi'),
 (0.7053076028823853, 'forsaken'),
 (0.6977889537811279, 'world'),
 (0.6941515803337097, 'godforsaken'),
 (0.6864916682243347, 'worlds'),
 (0.6546972393989563, 'unfair'),
 (0.6520710587501526, 'souls'),
 (0.6464097499847412, 'scum')]