### **Representation of text using Tf-Idf :-**

In [1]:
import pandas as pd
import spacy

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
texts = [
    "Innovative problem solver with a strong technical mindset",
    "Passionate about data science and artificial intelligence",
    "Experienced in machine learning and real-time systems",
    "Skilled in Python, web development, and database handling",
    "Strong team player with leadership and communication skills",
    "Focused on building impactful and sustainable solutions",
    "Always eager to learn and adapt to new technologies"
]

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
v.fit(texts)
transform_output = v.transform(texts)

In [9]:
print(transform_output.toarray()[0].shape)
transform_output.toarray()[0]

(45,)

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.39596322, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.39596322, 0.        , 0.        ,
       0.        , 0.        , 0.39596322, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.39596322,
       0.32868348, 0.        , 0.        , 0.        , 0.39596322,
       0.        , 0.        , 0.        , 0.        , 0.32868348])

In [6]:
print(v.vocabulary_)

{'innovative': 16, 'problem': 27, 'solver': 34, 'with': 44, 'strong': 35, 'technical': 39, 'mindset': 22, 'passionate': 25, 'about': 0, 'data': 7, 'science': 30, 'and': 3, 'artificial': 4, 'intelligence': 17, 'experienced': 11, 'in': 15, 'machine': 21, 'learning': 20, 'real': 29, 'time': 41, 'systems': 37, 'skilled': 31, 'python': 28, 'web': 43, 'development': 9, 'database': 8, 'handling': 13, 'team': 38, 'player': 26, 'leadership': 18, 'communication': 6, 'skills': 32, 'focused': 12, 'on': 24, 'building': 5, 'impactful': 14, 'sustainable': 36, 'solutions': 33, 'always': 2, 'eager': 10, 'to': 42, 'learn': 19, 'adapt': 1, 'new': 23, 'technologies': 40}

In [7]:
len(v.vocabulary_)

45

In [8]:
v.get_feature_names_out()

array(['about', 'adapt', 'always', 'and', 'artificial', 'building',
       'communication', 'data', 'database', 'development', 'eager',
       'experienced', 'focused', 'handling', 'impactful', 'in',
       'innovative', 'intelligence', 'leadership', 'learn', 'learning',
       'machine', 'mindset', 'new', 'on', 'passionate', 'player',
       'problem', 'python', 'real', 'science', 'skilled', 'skills',
       'solutions', 'solver', 'strong', 'sustainable', 'systems', 'team',
       'technical', 'technologies', 'time', 'to', 'web', 'with'],
      dtype=object)

In [9]:
c = v.vocabulary_.get("about")
print(c)

0

In [10]:
all_features = v.get_feature_names_out()

for word in all_features:
    indx = v.vocabulary_.get(word)
    print(f"{word} {v.idf_[indx]}")

about 2.386294361119891
adapt 2.386294361119891
always 2.386294361119891
and 1.1335313926245225
artificial 2.386294361119891
building 2.386294361119891
communication 2.386294361119891
data 2.386294361119891
database 2.386294361119891
development 2.386294361119891
eager 2.386294361119891
experienced 2.386294361119891
focused 2.386294361119891
handling 2.386294361119891
impactful 2.386294361119891
in 1.9808292530117262
innovative 2.386294361119891
intelligence 2.386294361119891
leadership 2.386294361119891
learn 2.386294361119891
learning 2.386294361119891
machine 2.386294361119891
mindset 2.386294361119891
new 2.386294361119891
on 2.386294361119891
passionate 2.386294361119891
player 2.386294361119891
problem 2.386294361119891
python 2.386294361119891
real 2.386294361119891
science 2.386294361119891
skilled 2.386294361119891
skills 2.386294361119891
solutions 2.386294361119891
solver 2.386294361119891
strong 1.9808292530117262
sustainable 2.386294361119891
systems 2.386294361119891
team 2.386294361119891
technical 2.386294361119891
technologies 2.386294361119891
time 2.386294361119891
to 2.386294361119891
web 2.386294361119891
with 1.9808292530117262

In [11]:
print(len(texts[1])) 
texts[1]

57

'Passionate about data science and artificial intelligence'

In [12]:
print(transform_output[1].toarray().shape)
transform_output[1].toarray()                     # it give 2 d matrix

(1, 45)

array([[0.40078176, 0.        , 0.        , 0.19037832, 0.40078176,
        0.        , 0.        , 0.40078176, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40078176, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.40078176, 0.        , 0.        , 0.        , 0.        ,
        0.40078176, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ]])

### **Apply on emotion dataset to find the emotion in data:-**

In [13]:
import pandas as pd

df = pd.read_csv("emotion_dataset/train.txt", header=None,names=["text"])
df.head()

                                                text
0                    i didnt feel humiliated;sadness
1  i can go from feeling so hopeless to so damned...
2  im grabbing a minute to post i feel greedy wro...
3  i am ever feeling nostalgic about the fireplac...
4                         i am feeling grouchy;anger

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    16000 non-null  object
dtypes: object(1)
memory usage: 125.1+ KB

In [15]:
df[["text","label"]] = df["text"].str.split(";",expand=True)
df.head()

                                                text    label
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    16000 non-null  object
 1   label   16000 non-null  object
dtypes: object(2)
memory usage: 250.1+ KB

In [17]:
df.label.value_counts()

label
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [18]:
df["label_num"] = df["label"].map({
    "joy": 0,
    "sadness": 1,
    "anger": 2,
    "fear": 3,
    "love": 4,
    "surprise" : 5
})
df.head()

                                                text    label  label_num
0                            i didnt feel humiliated  sadness          1
1  i can go from feeling so hopeless to so damned...  sadness          1
2   im grabbing a minute to post i feel greedy wrong    anger          2
3  i am ever feeling nostalgic about the fireplac...     love          4
4                               i am feeling grouchy    anger          2

In [19]:
NEGATIONS = {
    "no",
    "not",
    "never",
    "none",
    "nothing",
    "nowhere",
    "neither",
    "nor",
    "without"
}
def prepros(doc):
    tokens = []

    negate_count = 0 

    for token in doc:

        if token.is_punct:
            negate_count = 0
            continue

        if token.dep_ == "neg" or token.text.lower() in NEGATIONS:
            tokens.append("not")
            negate_count = 1
            continue

        if token.is_stop:
            continue

        lemma = token.lemma_.lower()

        if negate_count > 0:
            lemma = "not_" + lemma
            negate_count -= 1

        tokens.append(lemma)

    return " ".join(tokens)

In [ ]:
# docs = nlp.pipe(df["text"], batch_size=1000)
# df["prepros_text"] = [prepros(doc) for doc in docs]
# df.to_csv("prepros_emotion.csv",index=False)

In [25]:
df = pd.read_csv("prepros_emotion.csv")
df.head()

,text,label,label_num,prepros_text
0,i didnt feel humiliated,sadness,1,not not_feel humiliated
1,i can go from feeling so hopeless to so damned...,sadness,1,feel hopeless damned hopeful care awake
2,im grabbing a minute to post i feel greedy wrong,anger,2,m grab minute post feel greedy wrong
3,i am ever feeling nostalgic about the fireplac...,love,4,feel nostalgic fireplace know property
4,i am feeling grouchy,anger,2,feel grouchy

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train ,y_test =train_test_split(df.prepros_text,df.label_num,test_size=0.20,stratify=df.label_num,random_state=2026)
print(x_train.shape)
print(y_test.shape)

(12800,)
(3200,)

In [27]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
pipeline = Pipeline([
    ("tfidf",TfidfVectorizer(ngram_range=(1,2))),
    ("nb",MultinomialNB(alpha=0.1))
])

In [28]:
pipeline.fit(x_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
                ('nb', MultinomialNB(alpha=0.1))])

In [29]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = pipeline.predict(x_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy: 0.768125
              precision    recall  f1-score   support

           0       0.73      0.93      0.82      1072
           1       0.74      0.92      0.82       933
           2       0.90      0.64      0.75       432
           3       0.87      0.61      0.72       387
           4       0.93      0.29      0.44       261
           5       1.00      0.12      0.22       115

    accuracy                           0.77      3200
   macro avg       0.86      0.59      0.63      3200
weighted avg       0.80      0.77      0.74      3200

In [30]:
from sklearn.ensemble import RandomForestClassifier
RF = Pipeline([
    ("tfidf",TfidfVectorizer(
        ngram_range=(1,2),
        max_features=3000)),
    ("rf",(RandomForestClassifier(
        n_estimators=200,
        max_depth=None,
        random_state=42,
        n_jobs=-1
    )))
])

RF.fit(x_train,y_train)
y_pred = RF.predict(x_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy: 0.8546875
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1072
           1       0.91      0.87      0.89       933
           2       0.88      0.84      0.86       432
           3       0.82      0.88      0.85       387
           4       0.81      0.67      0.73       261
           5       0.86      0.70      0.77       115

    accuracy                           0.85      3200
   macro avg       0.85      0.81      0.83      3200
weighted avg       0.86      0.85      0.85      3200

### **Testing Part : -**

In [31]:
reverse_mapping = {
    0: 'joy',
    1: 'sadness',
    2: 'anger',
    3: 'fear',
    4: 'love',
    5: 'surprise'
}

In [43]:
def testing(text):
    doc = nlp(text)
    prepros_text = prepros(doc)
    ans = pipeline.predict([prepros_text])[0]
    emotion = reverse_mapping[ans]
    return emotion

text = "I can’t stop smiling today because everything is finally going my way."
testing(text)

'sadness'

In [44]:
text = "I am not angry, just disappointed."
testing(text)

'anger'

In [45]:
tests = [
    "I feel very happy and satisfied with my life right now.",
    "I am not happy with how things turned out.",
    "I am extremely angry about how unfair this situation is.",
    "I am scared that something bad might happen to me.",
    "I truly care about you and feel deeply connected to you.",
    "I never expected this news, it completely shocked me."
]

for t in tests:
    print(t, "->", testing(t))

I feel very happy and satisfied with my life right now. -> joy
I am not happy with how things turned out. -> sadness
I am extremely angry about how unfair this situation is. -> anger
I am scared that something bad might happen to me. -> sadness
I truly care about you and feel deeply connected to you. -> sadness
I never expected this news, it completely shocked me. -> sadness