In [2]:
import spacy 
nlp = spacy.load("en_core_web_lg")

In [8]:
doc = nlp("hey yuvraj")
doc.vector

array([-5.52849919e-02,  2.59245008e-01,  1.00600004e-01, -1.67513013e-01,
       -3.62399966e-02,  5.39650023e-02,  2.01686993e-01, -5.92994988e-01,
        3.16538483e-01,  6.76499605e-02, -4.77510020e-02, -4.96214986e-01,
       -2.37857491e-01, -5.18014967e-01,  2.02859998e-01,  1.66149996e-02,
       -8.60049948e-03, -4.54849988e-01,  2.91913509e-01,  2.32824519e-01,
       -3.05526495e-01,  1.11604497e-01,  3.98914993e-01,  7.03144968e-02,
        1.50267497e-01,  2.37004980e-01,  6.72665015e-02, -7.22950026e-02,
        6.23274982e-01,  3.10823500e-01, -1.12839997e-01, -1.03100002e-01,
        1.11208498e-01,  9.41450000e-02, -6.90000057e-01,  2.38649994e-02,
       -1.53208509e-01,  1.73900016e-02, -4.65480030e-01,  2.92851985e-01,
       -1.03917502e-01, -4.69789982e-01, -3.54364991e-01, -3.47905010e-01,
        9.32089984e-02,  2.84099951e-02, -3.95999849e-03, -7.43879974e-02,
       -1.86450034e-02,  2.06074998e-01,  1.09759793e-01,  2.89534986e-01,
       -6.68934956e-02, -8.57249945e-02, -4.76089984e-01,  2.66839981e-01,
        8.36200118e-02,  3.05440009e-01, -2.25814998e-01,  2.80399993e-03,
       -5.07434964e-01,  2.08316997e-01, -2.20239997e-01, -6.75000250e-04,
       -1.81994997e-02, -5.74149936e-02, -1.60650015e-02,  3.42724979e-01,
        4.13755000e-01, -3.68224978e-01,  2.20149994e-01,  2.61784494e-02,
        1.18955351e-01, -5.73895015e-02,  3.20625007e-01, -2.67670482e-01,
        4.32960004e-01,  2.75470018e-01,  7.49160528e-01,  1.78950131e-02,
       -2.53023982e-01,  3.07155013e-01, -1.08735994e-01,  4.84869987e-01,
       -1.49625510e-01, -6.29145056e-02,  9.98139977e-01, -9.11980033e-01,
       -2.47648999e-01, -6.76465034e-02, -7.13650063e-02, -9.87669975e-02,
       -6.18529975e-01,  1.40271008e-01,  2.77695000e-01,  1.39089659e-01,
        2.04369992e-01, -1.71912491e-01, -2.42432505e-01,  7.50370026e-02,
        3.17645520e-01,  6.65000081e-03,  5.14384992e-02,  2.52500027e-02,
       -1.65999979e-02, -6.63014948e-01, -2.24323496e-01, -1.23765007e-01,
       -2.44334996e-01, -2.40765005e-01, -1.03355005e-01, -2.12920010e-01,
        1.80386007e-01, -8.94867480e-02,  3.20044994e-01,  6.14274979e-01,
        5.04171014e-01, -1.39774993e-01, -2.72119999e-01, -4.04115021e-01,
        1.66749954e-02, -3.53379995e-01, -8.22350085e-02,  6.78000078e-02,
       -6.29991293e-04,  3.42755020e-01,  6.33799955e-02, -1.35081008e-01,
       -2.53679067e-01,  4.43149984e-01, -1.02734499e-01, -2.49864995e-01,
        1.20001949e-01, -1.05295002e-01,  3.63879979e-01, -2.04749003e-01,
        3.12279999e-01,  1.02434993e-01, -2.99740016e-01, -1.01303995e-01,
       -1.85641003e+00,  5.58890030e-02,  4.20425013e-02,  5.84225059e-02,
       -6.13855004e-01, -8.04700032e-02, -6.25376478e-02,  3.74679983e-01,
       -2.33899996e-01, -1.35150030e-02,  1.53961599e-01, -1.41960010e-02,
        2.83554018e-01,  1.98425010e-01,  1.50317997e-01,  1.57030001e-01,
        9.22700018e-02, -2.67974496e-01, -3.84065002e-01,  2.21530005e-01,
        4.15692985e-01, -3.22645277e-01,  1.63044989e-01, -4.89234999e-02,
       -4.48800027e-02,  1.34768501e-01, -1.06899999e-01,  1.64692894e-01,
       -1.37803003e-01,  2.17085004e-01, -3.86605024e-01, -5.92922032e-01,
       -1.58944994e-01, -1.10764995e-01,  1.49483502e-01, -5.33050001e-01,
       -2.48454005e-01, -1.07170999e-01, -8.75744969e-02, -9.09774974e-02,
       -6.01658523e-01, -1.90754995e-01,  3.59510005e-01, -2.71889985e-01,
        1.32379979e-02, -2.35169996e-02,  4.59704995e-01, -6.62000030e-02,
       -4.69822995e-02,  2.05907002e-01,  4.22000021e-01, -3.67920011e-01,
       -6.56249970e-02, -5.12854993e-01, -1.22084998e-01,  2.86999978e-02,
        4.41127986e-01,  2.85830021e-01,  4.64309990e-01,  1.10420495e-01,
       -1.42501503e-01, -3.27275008e-01,  9.58575010e-02, -4.81164992e-01,
        1.76394999e-01, -1.72934994e-01,  5.17064989e-01, -2.17743501e-01,
        5.89329958e-01, -6.70125037e-02, -5.72229981e-01, -1.33304998e-01,
        3.62645015e-02, -3.10314983e-01, -5.38849980e-02, -2.22430497e-01,
        3.12538981e-01, -2.47269988e-01,  4.74472493e-01,  1.07067496e-01,
       -8.06154981e-02,  1.71284497e-01,  2.84561515e-01, -1.50744990e-02,
        2.29249999e-01,  7.88499415e-03, -3.11964035e-01, -1.00149997e-01,
       -1.30586997e-01, -2.54739493e-01,  1.04200095e-02,  1.04756489e-01,
       -2.32656494e-01, -1.11449994e-02, -3.23955506e-01,  3.85865003e-01,
       -1.75940499e-01,  2.76369900e-01, -2.88125008e-01,  1.73547506e-01,
       -3.92170012e-01,  1.58902496e-01,  3.36115003e-01,  3.51734996e-01,
        1.14068501e-01,  2.02335000e-01,  6.55725002e-01,  1.76485002e-01,
       -3.27026993e-01,  3.08056891e-01,  2.29039997e-01, -2.25889981e-01,
       -3.72345001e-01,  5.95974997e-02, -1.05160996e-01, -4.92499992e-02,
       -3.32955003e-01, -5.74019998e-02, -4.29191977e-01, -1.79744989e-01,
        3.14556986e-01, -1.67577490e-01,  3.19799989e-01, -1.24741003e-01,
       -1.63110018e-01, -8.75700042e-02,  8.80115032e-02,  2.90969998e-01,
        1.03014499e-01,  3.49749982e-01, -2.35145003e-01, -1.93654001e-01,
       -2.89009988e-01,  3.74534011e-01,  7.32394978e-02,  1.92878008e-01,
       -3.98050025e-02, -1.41047001e-01,  8.02499950e-02,  3.75929505e-01,
       -1.95944995e-01,  4.54999506e-03, -5.45629978e-01,  2.51584984e-02,
       -1.36424992e-02, -8.22274983e-02,  2.96193480e-01,  1.25155002e-01,
       -8.02549943e-02,  7.66144991e-02,  5.61412454e-01, -5.01654983e-01,
       -1.52860001e-01, -1.91566497e-01,  3.54192019e-01,  1.59230009e-01,
       -3.67354512e-01, -1.44996002e-01, -3.51395011e-01, -1.44525006e-01],
      dtype=float32)

In [11]:
test_token = nlp("yuvraj")
doc = nlp("person king poor hero corrupt queen happy")
for token in doc:
    print(f"{token.text} <-> {test_token.text} : ",token.similarity(test_token))

person <-> yuvraj :  -0.09439872950315475
king <-> yuvraj :  0.10194991528987885
poor <-> yuvraj :  0.008155187591910362
hero <-> yuvraj :  0.0901726707816124
corrupt <-> yuvraj :  0.03941097483038902
queen <-> yuvraj :  0.08764993399381638
happy <-> yuvraj :  -0.01011898834258318

In [12]:
import pandas as pd 
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [13]:
df["num_review"] = df["review"].apply(lambda x : nlp(x).vector)
df.head()

,review,sentiment,num_review
0,One of the other reviewers has mentioned that ...,positive,"[-0.04449084, 0.17363322, -0.13140342, -0.0635..."
1,A wonderful little production. <br /><br />The...,positive,"[-0.03195821, 0.14270347, -0.117409535, -0.045..."
2,I thought this was a wonderful way to spend ti...,positive,"[-0.014198674, 0.1675451, -0.10874847, -0.0810..."
3,Basically there's a family where a little boy ...,negative,"[-0.015863303, 0.07181742, -0.14372607, -0.049..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"[0.012670993, 0.14197588, -0.12925181, -0.0783..."

In [14]:
df["num_sentiment"] = df["sentiment"].map({
    "positive" : 0,
    "negative" : 1
})
df.head()

,review,sentiment,num_review,num_sentiment
0,One of the other reviewers has mentioned that ...,positive,"[-0.04449084, 0.17363322, -0.13140342, -0.0635...",0
1,A wonderful little production. <br /><br />The...,positive,"[-0.03195821, 0.14270347, -0.117409535, -0.045...",0
2,I thought this was a wonderful way to spend ti...,positive,"[-0.014198674, 0.1675451, -0.10874847, -0.0810...",0
3,Basically there's a family where a little boy ...,negative,"[-0.015863303, 0.07181742, -0.14372607, -0.049...",1
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"[0.012670993, 0.14197588, -0.12925181, -0.0783...",0

In [15]:
df.to_csv("Embed_IMDB_data.csv",index=False)

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.num_review, df.num_sentiment , test_size=0.20, random_state = 2026)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

(40000,)
(40000,)
(10000,)

In [41]:
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   review         50000 non-null  object
 1   sentiment      50000 non-null  object
 2   num_review     50000 non-null  object
 3   num_sentiment  50000 non-null  int64
dtypes: int64(1), object(3)
memory usage: 1.5+ MB
None

,review,sentiment,num_review,num_sentiment
0,One of the other reviewers has mentioned that ...,positive,"[-0.04449084, 0.17363322, -0.13140342, -0.0635...",0
1,A wonderful little production. <br /><br />The...,positive,"[-0.03195821, 0.14270347, -0.117409535, -0.045...",0
2,I thought this was a wonderful way to spend ti...,positive,"[-0.014198674, 0.1675451, -0.10874847, -0.0810...",0
3,Basically there's a family where a little boy ...,negative,"[-0.015863303, 0.07181742, -0.14372607, -0.049...",1
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,"[0.012670993, 0.14197588, -0.12925181, -0.0783...",0

In [42]:
x_train.info()

<class 'pandas.core.series.Series'>
Index: 40000 entries, 28471 to 2305
Series name: num_review
Non-Null Count  Dtype
--------------  -----
40000 non-null  object
dtypes: object(1)
memory usage: 625.0+ KB

In [43]:
x_train.shape

(40000,)

In [44]:
x_train.values

array([array([-2.98895370e-02,  1.54987648e-01, -1.37976021e-01, -6.35615066e-02,
               1.07768968e-01,  6.42738119e-03,  5.26816165e-03, -1.28613174e-01,
              -3.09621505e-02,  2.06127620e+00, -1.61896914e-01,  7.37992376e-02,
               8.09331834e-02, -4.23020199e-02, -1.15892969e-01, -5.12166396e-02,
              -4.34085205e-02,  9.50112224e-01, -1.68320760e-01, -3.60189751e-02,
               9.87766962e-03, -4.78592627e-02, -2.46050227e-02, -3.42058651e-02,
              -1.13419453e-02,  1.48349879e-02, -5.63086569e-02, -4.58128229e-02,
               6.55308366e-02, -8.66212100e-02, -5.07568866e-02,  6.27445132e-02,
              -8.34937990e-02,  8.68561715e-02,  1.12393454e-01, -8.45967308e-02,
               1.18897650e-02,  6.97574168e-02, -5.85491471e-02, -4.46690321e-02,
               7.64647825e-03,  6.02941774e-02,  6.34283526e-03, -8.78849328e-02,
               7.30203241e-02,  3.32262442e-02, -1.46504998e-01, -1.74148232e-02,
              -1.71496067e-02,  3.00209341e-03, -4.57196869e-02,  4.43380773e-02,
              -1.21546192e-02, -1.66264530e-02,  5.17804734e-02,  2.90096197e-02,
               3.49098491e-03, -8.29402432e-02,  2.01267190e-02, -9.45117995e-02,
              -4.16433960e-02, -3.27224620e-02, -7.77352834e-03,  1.45673156e-01,
               4.15750854e-02, -1.00888804e-01, -4.66186693e-03,  3.48267891e-02,
               1.71212535e-02,  1.19043626e-01,  6.40054420e-02,  8.70099105e-03,
               1.71453342e-01, -1.33205131e-02,  5.57393692e-02,  5.90994954e-03,
               4.52197455e-02, -4.95344177e-02, -3.59898247e-02,  1.79285988e-01,
              -1.17180320e-02,  5.02000079e-02, -1.32427394e-01,  3.04527674e-03,
               1.70867499e-02, -1.61519960e-01,  8.30420405e-02, -1.80591971e-01,
               1.87124431e-01,  3.67643386e-02, -1.27581462e-01,  2.10273899e-02,
              -4.40924168e-02,  3.96886617e-02,  9.22836810e-02, -2.97238100e-02,
              -3.55435535e-02, -6.11090995e-02, -1.25848548e-02, -4.63605821e-02,
              -1.31687401e-02,  7.02680722e-02, -7.83496574e-02, -6.98015690e-02,
               1.03803910e-01, -5.63168645e-01,  8.10418651e-02, -1.32931424e-02,
               1.67062096e-02, -4.06253710e-03,  4.62848805e-02, -1.28900841e-01,
               6.39526248e-02, -9.49852169e-02,  3.16307694e-03, -1.75541565e-02,
               9.01308190e-03, -7.63583696e-03, -2.98501253e-02, -2.94758659e-02,
               3.89335714e-02, -4.25982252e-02,  2.57450272e-03, -3.00284028e-02,
              -2.66720634e-02,  8.49065706e-02, -2.58949287e-02, -1.07524626e-01,
               3.94572616e-02, -1.88559070e-02, -1.18118413e-02, -2.80089714e-02,
              -8.14860687e-02,  5.07924743e-02,  8.71612057e-02,  4.86266166e-02,
              -3.60873938e-02,  1.37855578e-02, -1.14779221e-02, -7.24947592e-03,
              -1.37661791e+00,  9.79706645e-02,  1.14507981e-01,  3.22224870e-02,
              -5.60531858e-03, -3.92168984e-02, -4.60443012e-02,  2.37621870e-02,
               2.67258938e-02, -3.92732322e-02, -2.56062262e-02,  5.36448620e-02,
               5.76845147e-02,  7.61398580e-04, -3.49627845e-02, -2.15673260e-02,
              -8.47062096e-02, -8.41953680e-02, -1.46920364e-02, -6.56089708e-02,
              -4.06137034e-02,  6.03233557e-03, -1.37145547e-02, -2.55703758e-02,
              -5.86714521e-02, -1.28845677e-01,  3.89258526e-02, -4.60348390e-02,
               1.08889684e-01, -7.81465881e-03, -1.21099735e-02, -5.18994518e-02,
               5.22305295e-02, -7.78680891e-02, -6.27043992e-02,  3.00274808e-02,
              -4.87549156e-02, -6.50073867e-03, -3.47605301e-03, -7.89510757e-02,
              -2.76979432e-03, -6.52806163e-02, -1.04766689e-01, -6.63410947e-02,
              -5.63988611e-02, -1.51958852e-03, -4.22434434e-02, -7.07362778e-03,
               7.02689737e-02,  1.46563072e-02, -3.58973001e-03,  1.48152397e-03,
              -7.04359859e-02,  4.81338501e-02,  1.94360819e-02,  6.93485811e-02,
              -3.26808617e-02, -1.19062416e-01, -1.38174528e-02,  1.55817628e-01,
              -1.58688668e-02, -3.83326411e-02, -5.92035428e-02, -1.03252800e-02,
               1.42164305e-01,  2.46314462e-02,  6.66969344e-02, -2.57322751e-02,
               4.56966311e-02,  8.89799185e-03, -7.44634643e-02, -5.07828929e-02,
              -2.79032458e-02, -1.36532247e-01,  6.65069297e-02,  1.23016901e-01,
              -2.46075075e-02,  1.11549934e-02, -1.56877115e-01, -2.78278962e-02,
               2.45977901e-02,  3.58336568e-02, -6.76072612e-02,  2.83542182e-02,
               2.11218861e-03, -3.69375274e-02, -1.76999662e-02,  1.05524875e-01,
               2.53151655e-02, -4.49515792e-05, -8.99196118e-02,  1.14139533e-02,
               1.10386297e-01,  7.63014406e-02, -7.25354850e-02, -5.31819910e-02,
               1.63282733e-02, -6.50057867e-02, -8.05178061e-02,  7.68768564e-02,
               1.33211426e-02,  4.82048690e-02,  5.03298081e-02,  7.29986802e-02,
               1.10145807e-01, -1.41537666e-01, -6.27302080e-02, -9.00807381e-02,
              -1.16256475e-01,  1.28550425e-01,  3.34870368e-02, -3.70752588e-02,
              -1.32189477e-02, -3.18019278e-02,  1.48747712e-02,  1.98980108e-01,
               9.31665897e-02, -1.38921700e-02, -3.66394781e-02,  4.70086262e-02,
               9.14033577e-02,  1.40124828e-01,  3.47459950e-02,  2.42171325e-02,
               1.00697175e-01, -2.67278366e-02, -2.24235915e-02,  2.95485146e-02,
               2.87311405e-01,  4.47035469e-02,  1.72420200e-02, -4.80368137e-02,
              -9.50993225e-02, -1.38312161e-01, -1.07486516e-01,  3.85083072e-03,
               1.69763174e-02,  2.83014439e-02,  1.60260797e-02,  1.91783160e-01,
               1.80795759e-01,  3.45294140e-02,  1.70741361e-02, -7.40888491e-02,
              -5.99022508e-02, -5.84837645e-02,  1.01406120e-01, -8.44664574e-02,
               1.38331100e-01, -4.76652347e-02, -1.23650946e-01,  1.79238711e-02,
               2.41947244e-03, -5.77338859e-02,  1.91406924e-02,  2.32740417e-02,
              -4.95251790e-02, -1.67336613e-02, -5.61207905e-03,  6.84460253e-02],
             dtype=float32)                                                       ,
       array([-3.57278548e-02,  1.89721599e-01, -1.58022404e-01, -4.64615710e-02,
               5.37657812e-02,  3.26906443e-02, -2.26849326e-04, -1.72321141e-01,
              -4.30323835e-03,  2.16952562e+00, -1.38005272e-01,  8.23879316e-02,
               8.03616419e-02, -5.32952771e-02, -1.18699729e-01, -4.85718772e-02,
              -4.97681126e-02,  9.05538797e-01, -1.57984719e-01, -6.25938773e-02,
              -3.15916985e-02, -5.32519184e-02, -3.65865752e-02, -1.77025404e-02,
               2.94806026e-02,  3.95731889e-02, -4.26120684e-02, -8.58478546e-02,
               4.07558940e-02, -1.27096191e-01, -9.42020118e-02,  8.00425559e-02,
              -5.98642193e-02,  5.24735302e-02,  3.27132568e-02, -6.35144264e-02,
               1.92071479e-02,  5.17543554e-02, -1.00947715e-01, -9.57195386e-02,
               1.28897261e-02,  7.56950229e-02,  3.62989977e-02, -7.53663331e-02,
               7.21332282e-02,  4.22675386e-02, -1.38115093e-01, -1.42826214e-02,
              -2.10000258e-02,  2.34087128e-02, -1.12651996e-02,  5.45040257e-02,
               1.43125560e-02, -3.18923518e-02,  8.68161693e-02,  3.60142924e-02,
              -2.21184772e-02, -1.57333881e-01,  2.57062558e-02, -9.81263146e-02,
              -7.22562894e-02, -6.37010559e-02, -3.87414917e-02,  1.62169635e-01,
               3.01360972e-02, -1.31394118e-01, -4.46617194e-02,  2.85844076e-02,
               2.31458135e-02,  1.07408926e-01,  1.02707945e-01,  6.98545575e-02,
               1.16774514e-01, -4.05394100e-02,  6.31170124e-02,  3.62718962e-02,
               6.46654814e-02, -8.86083171e-02, -7.25715086e-02,  1.81501031e-01,
               2.58631166e-02,  3.44645046e-02, -1.42738312e-01, -3.40317339e-02,
               3.58357839e-02, -1.98243499e-01,  1.94714535e-02, -2.74758488e-01,
               2.23619580e-01, -1.45481862e-02, -1.46421641e-01,  3.09627112e-02,
              -6.04912452e-02,  7.44445920e-02,  1.18464053e-01, -4.33759131e-02,
               1.77660100e-02, -3.50667499e-02,  1.89861492e-03, -8.94689932e-03,
              -3.71796787e-02,  2.51925588e-02, -9.43158567e-02, -5.52649610e-02,
               1.20610580e-01, -6.27236903e-01,  6.52610436e-02, -8.79364088e-03,
               2.15142872e-03, -1.00684934e-03,  2.68725380e-02, -1.36927351e-01,
               7.13226572e-02, -6.93085045e-02, -4.23301607e-02, -1.53082963e-02,
              -1.15424721e-02,  7.97407795e-03, -2.08013095e-02, -1.42552583e-02,
               3.57445814e-02, -1.17047727e-01, -1.05984025e-02, -3.29537168e-02,
               4.01117243e-02,  7.46134967e-02, -3.78469490e-02, -1.36274293e-01,
              -1.03091113e-02, -2.05081385e-02, -5.67220477e-03,  4.03265432e-02,
              -6.87545016e-02,  9.81550440e-02,  1.14083506e-01,  6.75965054e-03,
              -7.02418387e-03, -3.49827372e-02,  3.86868836e-04, -4.78275679e-02,
              -1.31783342e+00,  1.08656943e-01,  1.13025106e-01,  3.75466794e-02,
               6.46089716e-03, -8.21914747e-02, -9.41777080e-02, -2.73643155e-02,
               7.75520876e-02, -6.47224337e-02,  4.27104672e-03,  4.47908156e-02,
               8.10359269e-02, -2.44414271e-03, -7.25651905e-02, -7.15023726e-02,
              -1.02056533e-01, -6.54395968e-02,  2.65646214e-03, -7.72183314e-02,
              -5.59570827e-02, -2.61815172e-02, -3.22336890e-02, -4.35438827e-02,
              -1.01738155e-01, -1.31550506e-01,  1.33556442e-03, -6.10546544e-02,
               1.16559193e-01, -2.96804383e-02, -1.95727739e-02, -4.39556688e-02,
               7.77160823e-02, -1.21391088e-01, -5.61716668e-02,  3.23062800e-02,
              -2.25413721e-02, -3.65292244e-02,  5.63527737e-03, -7.02574924e-02,
              -1.37209904e-03, -7.14285597e-02, -1.10155843e-01, -3.27992849e-02,
              -8.09573457e-02, -1.68778319e-02, -8.43078643e-02, -4.33568086e-04,
               5.83777055e-02,  2.70226691e-02, -3.81525457e-02,  3.01715583e-02,
              -1.42122880e-01,  5.27933128e-02,  6.14800081e-02,  5.92740215e-02,
              -8.06846768e-02, -1.32871374e-01,  3.33168148e-03,  1.35563254e-01,
              -5.09804394e-03, -5.21956384e-02, -1.09566242e-01, -1.92008838e-02,
               1.28203198e-01,  4.62995581e-02,  6.44458905e-02, -3.15334760e-02,
               6.17173724e-02,  5.24816848e-02, -3.23121734e-02, -5.53081371e-02,
              -2.30038967e-02, -1.94627956e-01,  8.64149854e-02,  1.66130260e-01,
              -9.65030212e-03,  3.35156173e-02, -1.81916058e-01, -4.14121933e-02,
               6.17357604e-02,  8.50642659e-03, -2.63694003e-02,  4.04195376e-02,
               1.95194576e-02,  1.00190483e-03,  3.58483419e-02,  1.05956107e-01,
              -3.65789048e-03, -2.07810160e-02, -1.20559648e-01,  6.56950623e-02,
               1.13726854e-01,  9.29003060e-02, -2.65550744e-02, -6.59802929e-02,
              -1.26562333e-02, -6.52943775e-02, -9.45755318e-02,  1.17613658e-01,
               5.83532266e-02,  3.65426540e-02,  2.85881534e-02,  8.52374956e-02,
               9.80245769e-02, -1.61040246e-01, -6.00468777e-02, -1.19964510e-01,
              -9.13529098e-02,  9.59218591e-02,  3.08211688e-02, -6.24141581e-02,
              -1.56514309e-02, -2.69923322e-02,  2.25462932e-02,  1.61736608e-01,
               1.05105974e-01, -6.18905798e-02, -9.91937611e-03,  2.02841926e-02,
               1.37018934e-01,  1.81439757e-01,  2.87442226e-02,  7.27142468e-02,
               1.36949182e-01, -2.58843340e-02, -1.21156387e-02,  7.42683858e-02,
               3.79330277e-01,  4.36993837e-02,  1.34260297e-01, -3.63634042e-02,
              -1.11040622e-01, -1.29071161e-01, -1.28171757e-01,  2.52664834e-02,
               1.50513649e-02, -2.98155267e-02,  7.32183224e-03,  2.39489913e-01,
               1.90611735e-01,  4.62830476e-02,  5.45799620e-02, -7.14147016e-02,
              -3.85299101e-02, -7.12659806e-02,  1.06902801e-01, -4.97916713e-02,
               1.38370648e-01, -2.60574892e-02, -1.58831909e-01,  4.69928756e-02,
               4.56113694e-03, -2.87636388e-02,  7.10429475e-02,  2.79087760e-02,
              -5.49214929e-02, -5.61944768e-02,  4.96677794e-02,  8.33620876e-02],
             dtype=float32)                                                       ,
       array([-1.86854636e-03,  1.77989095e-01, -9.10271630e-02, -6.05707876e-02,
               9.84432250e-02,  7.51953898e-03,  3.84992026e-02, -8.89229849e-02,
              -2.51465626e-02,  1.90382349e+00, -1.33350700e-01,  6.16330327e-03,
               5.89209981e-02, -7.42476135e-02, -5.23779243e-02, -4.65639457e-02,
              -3.27995010e-02,  8.03871453e-01, -1.11550637e-01, -8.21094960e-02,
              -3.27170976e-02, -5.36212921e-02, -4.53323200e-02, -1.62168685e-02,
               5.93221970e-02, -5.42774564e-03, -6.40771240e-02,  9.82078537e-03,
               1.42971864e-02, -1.55217843e-02, -3.76852304e-02,  6.75154924e-02,
              -8.80960077e-02,  8.58103931e-02,  8.92556161e-02, -6.84992000e-02,
              -5.03168404e-02,  6.23820163e-02, -7.79337287e-02, -1.86319612e-02,
              -1.62479971e-02,  6.70068786e-02,  2.10861024e-02, -3.27127129e-02,
               5.63304760e-02,  2.78275404e-02, -8.33301023e-02,  1.31983245e-02,
               9.76840630e-02,  2.04772558e-02,  1.77837233e-03,  3.94287892e-02,
              -3.10488860e-03, -3.06412727e-02,  8.50391388e-03,  4.41657864e-02,
               1.98977180e-02, -5.82338385e-02,  4.40165680e-03, -7.70514756e-02,
              -3.39971595e-02, -2.89211012e-02,  7.43337302e-03,  1.23748779e-01,
               2.17980929e-02, -7.26822391e-02, -2.85112336e-02,  1.07778059e-02,
               4.69970889e-03,  1.01952702e-01,  7.36861303e-02,  4.32698466e-02,
               5.72284199e-02,  1.35128237e-02,  5.80235682e-02, -1.14611657e-02,
               3.12685594e-02,  2.67128716e-03,  2.68750042e-02,  1.08088985e-01,
               2.01207236e-03,  8.77936259e-02, -8.67535546e-02, -3.17044929e-02,
               1.96973514e-02, -1.73583567e-01,  1.67302340e-02, -1.26884699e-01,
               1.07111797e-01,  2.85925101e-02, -7.50160068e-02,  1.99097265e-02,
              -8.43892572e-04,  3.32921674e-03,  1.24204837e-01, -9.67236534e-02,
               1.62792392e-02,  1.01930788e-02, -2.50323433e-02, -5.29978983e-02,
               8.57952144e-03,  2.78015193e-02, -1.23758391e-01, -4.27585840e-02,
               3.64145413e-02, -4.43650067e-01,  6.41778186e-02,  1.42077785e-02,
               9.31433067e-02, -5.56280091e-02,  2.77538579e-02, -6.23491257e-02,
               4.06899676e-02, -8.17155614e-02, -1.62143260e-02, -3.22697721e-02,
               4.46244851e-02,  2.79501118e-02,  4.42576269e-03, -1.72449164e-02,
               5.77292815e-02, -1.54912155e-02, -2.99369469e-02, -1.03709651e-02,
              -6.09734561e-03,  5.72204329e-02,  3.67391817e-02, -2.70674750e-02,
               8.73847865e-03, -6.16830727e-03,  4.23209975e-03, -1.16460212e-02,
              -2.54893005e-02, -1.65674184e-02,  5.79858832e-02,  1.67630110e-02,
              -2.82432158e-02,  8.92953854e-03,  1.82647295e-02, -3.72169986e-02,
              -1.10546553e+00,  3.48824561e-02,  8.87705758e-02,  1.54477870e-02,
              -2.42881980e-02,  1.29048980e-03,  1.59655325e-02, -1.98571105e-03,
               5.71307614e-02, -5.68394065e-02,  9.76377167e-04, -2.34503448e-02,
               8.80622342e-02, -3.58977052e-03, -6.80228472e-02, -1.06632803e-02,
              -8.33899081e-02, -4.32128757e-02, -1.95794664e-02, -6.09618351e-02,
              -2.83243451e-02, -8.03579390e-03,  1.27221388e-03, -5.95085360e-02,
              -6.06132299e-02, -1.31625533e-01,  2.27986351e-02, -6.39969856e-02,
               1.48604855e-01,  7.17040338e-03,  8.90019163e-03,  6.67829206e-03,
              -8.58371332e-03, -3.27687040e-02, -7.86034614e-02,  8.07414204e-03,
              -2.58957711e-03, -8.16078112e-03,  3.08237355e-02, -7.60711581e-02,
              -6.91132899e-03, -6.86928779e-02, -5.99716194e-02, -3.08026038e-02,
              -7.66635165e-02,  7.83117663e-04, -4.82584611e-02,  5.68914004e-02,
               4.58617024e-02, -6.20310307e-02, -1.80307589e-02,  4.50258702e-02,
              -4.94417138e-02,  4.49816622e-02, -4.33876738e-02,  6.76399544e-02,
              -4.53661680e-02, -7.24021569e-02, -2.83506326e-02,  1.31205589e-01,
              -5.81430607e-02, -4.92676422e-02, -4.94649485e-02,  1.45087782e-02,
               1.15834840e-01, -9.16850567e-03,  5.36472760e-02, -4.37741987e-02,
              -6.69045700e-03,  8.37706868e-03, -7.01520890e-02, -2.10697344e-03,
              -1.15530118e-02, -1.45773217e-01,  3.59666124e-02,  1.58026934e-01,
              -2.35006050e-03,  3.63679067e-03, -1.05470449e-01,  1.43395392e-02,
               1.76788587e-02,  5.74425347e-02, -3.06645483e-02,  2.91869510e-02,
               1.32545047e-02, -2.58260104e-03,  1.43764419e-02,  9.78462026e-02,
               4.06186692e-02,  6.76085278e-02, -1.04109250e-01,  6.18112125e-02,
               4.65329140e-02,  5.78790531e-02, -6.01583160e-02, -5.43306395e-02,
              -5.62340766e-02, -5.18513508e-02, -6.09993041e-02,  7.91700929e-02,
              -2.36350819e-02,  3.16618867e-02,  2.79664341e-02,  3.32078300e-02,
               3.62523422e-02, -6.40788227e-02, -8.46137702e-02, -8.38827714e-02,
              -1.14427604e-01,  2.98931100e-03,  5.05887643e-02,  1.01670753e-02,
              -2.45477688e-02, -4.06902917e-02,  1.60226040e-02,  1.56746536e-01,
               8.67121965e-02, -5.20551130e-02, -4.64819334e-02,  4.38323915e-02,
               8.81948397e-02,  1.50777653e-01, -2.36878823e-02,  1.36077285e-01,
               4.78943959e-02, -9.29681659e-02,  1.56924792e-03,  2.42697005e-03,
               1.51582956e-01, -4.21982184e-02, -3.45149189e-02, -2.44776085e-02,
              -7.74702877e-02, -1.05505742e-01, -7.55991563e-02, -9.16029420e-03,
               7.00192573e-03,  8.42469186e-03, -2.71837357e-02,  1.92788959e-01,
               1.85347706e-01,  6.20826222e-02,  5.88068133e-03, -4.29767706e-02,
              -2.42610965e-02, -6.12980612e-02,  1.00951731e-01, -7.59018809e-02,
               8.84830728e-02, -2.80067977e-02, -1.49939895e-01,  4.18673865e-02,
               3.80508527e-02, -9.20504797e-03,  2.56557520e-02,  1.61274355e-02,
              -6.44409738e-04, -5.82225882e-02, -3.66841117e-03, -4.86983964e-03],
             dtype=float32)                                                       ,
       ...,
       array([-1.17895575e-02,  1.28768817e-01, -1.58450454e-01, -9.50879306e-02,
               6.10420518e-02,  3.97701114e-02,  4.49314760e-03, -1.74832746e-01,
               1.35312416e-02,  2.19845629e+00, -1.58038691e-01,  7.09197596e-02,
               9.23464745e-02, -6.65348023e-02, -1.31282404e-01, -7.80639946e-02,
              -6.22528605e-02,  9.46304262e-01, -1.92605972e-01, -2.87761483e-02,
              -8.12459644e-03, -4.15823236e-02, -1.32293883e-03, -3.64528187e-02,
               7.75169069e-03,  1.84965413e-02, -8.52009952e-02, -8.92265737e-02,
               5.92893958e-02, -7.67825916e-02, -5.05568385e-02,  5.03117032e-02,
              -8.08345750e-02,  6.65234551e-02,  6.33585006e-02, -1.00812539e-01,
               1.99399516e-02,  4.38731052e-02, -1.08480573e-01, -5.61377369e-02,
               5.56844426e-03,  7.04881474e-02,  2.24102866e-02, -6.87179193e-02,
               8.33250508e-02,  4.33189981e-02, -1.55322194e-01, -2.21426729e-02,
               2.61406805e-02, -1.33137852e-02, -1.69921586e-05,  3.46301831e-02,
               8.58237781e-03, -3.88365462e-02,  1.97168961e-02,  4.15854827e-02,
              -2.55182702e-02, -1.25906378e-01,  2.13562958e-02, -5.49613014e-02,

In [48]:
import numpy as np
x_train_v = np.stack(x_train)
x_test_v = np.stack(x_test)

In [76]:
x_train_v.shape

(40000, 300)

In [50]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
x_train_scaled = scalar.fit_transform(x_train_v)
x_test_scaled = scalar.fit_transform(x_test_v)

In [60]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB(alpha=1)
nb.fit(x_train_scaled,y_train)

MultinomialNB(alpha=1)

In [61]:
from sklearn.metrics import classification_report,accuracy_score
y_pred = nb.predict(x_test_scaled)
print(f"Acuracy : {accuracy_score(y_test,y_pred)}")
print(classification_report(y_test,y_pred))

Acuracy : 0.7036
              precision    recall  f1-score   support

           0       0.71      0.69      0.70      5084
           1       0.69      0.71      0.70      4916

    accuracy                           0.70     10000
   macro avg       0.70      0.70      0.70     10000
weighted avg       0.70      0.70      0.70     10000

In [68]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric="euclidean")
knn.fit(x_train_v,y_train)

KNeighborsClassifier(metric='euclidean')

In [69]:
y_pred = knn.predict(x_test_v)
print(f"Acuracy : {accuracy_score(y_test,y_pred)}")
print(classification_report(y_test,y_pred))

Acuracy : 0.7596
              precision    recall  f1-score   support

           0       0.79      0.72      0.75      5084
           1       0.73      0.80      0.77      4916

    accuracy                           0.76     10000
   macro avg       0.76      0.76      0.76     10000
weighted avg       0.76      0.76      0.76     10000

In [70]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)
rf.fit(x_train_v,y_train)

RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)

In [71]:
y_pred = rf.predict(x_test_v)
print(f"Acuracy : {accuracy_score(y_test,y_pred)}")
print(classification_report(y_test,y_pred))

Acuracy : 0.8051
              precision    recall  f1-score   support

           0       0.80      0.81      0.81      5084
           1       0.81      0.80      0.80      4916

    accuracy                           0.81     10000
   macro avg       0.81      0.80      0.80     10000
weighted avg       0.81      0.81      0.81     10000

In [72]:
from catboost import CatBoostClassifier
cat = CatBoostClassifier(
    iterations=500,
    learning_rate=0.1,
    depth=6,
    loss_function="Logloss",   
    eval_metric="Accuracy",
    random_seed=42,
    verbose=100
)
cat.fit(x_train_v,y_train)

0:	learn: 0.7108250	total: 85.9ms	remaining: 42.9s
100:	learn: 0.8405250	total: 2.03s	remaining: 8.01s
200:	learn: 0.8720000	total: 3.88s	remaining: 5.77s
300:	learn: 0.8954250	total: 5.69s	remaining: 3.76s
400:	learn: 0.9141250	total: 7.45s	remaining: 1.84s
499:	learn: 0.9297250	total: 9.15s	remaining: 0us

In [73]:
y_pred = cat.predict(x_test_v)
print(f"Acuracy : {accuracy_score(y_test,y_pred)}")
print(classification_report(y_test,y_pred))

Acuracy : 0.8505
              precision    recall  f1-score   support

           0       0.85      0.85      0.85      5084
           1       0.85      0.85      0.85      4916

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

In [74]:
from xgboost import XGBClassifier
xgb = XGBClassifier(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)
xgb.fit(x_train_v,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=-1,
              num_parallel_tree=None, ...)

In [75]:
y_pred = xgb.predict(x_test_v)
print(f"Acuracy : {accuracy_score(y_test,y_pred)}")
print(classification_report(y_test,y_pred))

Acuracy : 0.8527
              precision    recall  f1-score   support

           0       0.86      0.85      0.86      5084
           1       0.85      0.85      0.85      4916

    accuracy                           0.85     10000
   macro avg       0.85      0.85      0.85     10000
weighted avg       0.85      0.85      0.85     10000

In [86]:
def testing(text):
    doc = nlp(text)
    vec = doc.vector
    v_2d = vec.reshape(1, -1)
    y = xgb.predict(v_2d)
    if(y==0):
        print("Positive")
    else:
        print("negative")

testing("Good performance, but the build quality is poor.")

negative