In [54]:
# from io import StringIO
import pandas as pd
import numpy as np

In [55]:
pd.read_csv('test.csv')

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99
0,15000,0.398169,2.143300,114.8780,3.816510,0.089995,1.042540,5.307310,1.767470,1.350300,...,0.040523,1.308520,0.065694,0.047387,-0.035951,0.281766,0.477826,1.62488,0.029438,-0.031790
1,15001,0.008505,2.349320,853.8810,5.231130,0.049947,1.107780,0.928617,0.293212,1.117650,...,0.080400,4.083920,0.047871,0.105594,0.030981,0.096044,3.408660,2.27766,-0.015950,0.093279
2,15002,2.767680,2.084530,148.9250,4.046420,0.007924,4.261860,1.295550,-0.310799,4.306960,...,0.078513,-0.250609,0.029606,0.092942,-0.044077,0.106987,3.987810,1.68461,1.205700,0.106042
3,15003,1.071190,5.919520,-64.0648,0.195529,0.079169,0.903287,4.935910,1.769730,1.766360,...,0.103638,0.938042,0.014003,0.050670,0.114732,0.405016,3.223190,4.58780,0.051759,0.094247
4,15004,0.068140,3.539450,-25.8223,5.739260,0.038304,3.349190,4.220190,1.177650,4.929340,...,0.106432,3.928190,0.700506,0.013716,0.033387,0.057754,3.433780,3.64833,0.076186,0.045207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,24995,-0.005145,3.001410,210.6070,0.994924,0.019112,2.783550,3.405270,1.108160,3.612990,...,0.017866,0.564076,0.041830,0.067117,0.095220,0.493235,2.321530,1.70168,1.191190,-0.013795
9996,24996,0.119577,4.266310,162.3760,1.245620,0.026891,1.119720,2.455950,1.892510,1.884320,...,0.038461,2.750980,0.095389,0.115835,-0.001519,0.329741,1.553460,4.93422,0.098288,0.059588
9997,24997,-0.074183,0.268787,199.6410,5.217750,-0.036501,3.469370,3.917630,3.325400,2.533160,...,0.093584,1.020830,0.017167,0.099463,0.097122,0.275216,0.421355,1.31525,0.168879,0.004827
9998,24998,-0.049194,4.064200,3400.6200,3.039560,0.089791,1.248200,1.868640,3.843320,-0.492011,...,0.049420,4.830970,0.128419,0.053590,0.044978,0.269863,4.731870,2.31149,0.082613,0.108157
9999,24999,0.024247,1.525240,140.1220,1.444970,0.110097,0.614881,4.020260,1.172260,-0.323853,...,-0.013819,5.423580,0.011909,0.113500,1.541270,0.085786,1.624360,2.99767,0.631893,-0.004036

In [56]:
# converting stirng into file format :-)

data = ('Columns1,Column2,columns\n'
    'a,B,1\n'
    'x,Y,2')
type(data)

str

In [57]:
from io import StringIO
StringIO(data)            # convrt string into file format :-

f = pd.read_csv(StringIO(data))
f

  Columns1 Column2  columns
0        a       B        1
1        x       Y        2

In [58]:
type(f)

pandas.core.frame.DataFrame

In [59]:
df = pd.read_csv('test.csv',usecols = ['id'	,'f0',	'f1',	'f2',	'f3'	,'f4'	,'f5']	)
h = df.head()

In [60]:
h.to_csv('test1.csv')
# without index
h.to_csv('test2.csv',index = False)

In [61]:
data = ('Columns1,Column2,columns3,column4\n'
    'a,B,1,2\n'
    'x,Y,2')
A = pd.read_csv(StringIO(data))

In [62]:
pd.isnull(A).sum()

Columns1    0
Column2     0
columns3    0
column4     1
dtype: int64

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10000 non-null  int64
 1   f0      10000 non-null  float64
 2   f1      10000 non-null  float64
 3   f2      10000 non-null  float64
 4   f3      10000 non-null  float64
 5   f4      10000 non-null  float64
 6   f5      10000 non-null  float64
dtypes: float64(6), int64(1)
memory usage: 547.0 KB

In [64]:
# change data type :-)
df = pd.read_csv(StringIO(data),dtype = 'object')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Columns1  2 non-null      object
 1   Column2   2 non-null      object
 2   columns3  2 non-null      object
 3   column4   1 non-null      object
dtypes: object(4)
memory usage: 192.0+ bytes

In [66]:
A = pd.read_csv('test.csv')
A['f0'][2]

2.76768

In [69]:
data = ('Columns1,Column2,columns3,column4\n'
    '1,2,3,4\n'
    '2,5,6')
A = pd.read_csv(StringIO(data))

In [70]:
# change data type :-)
df = pd.read_csv(StringIO(data),dtype = {'Columns1': int , 'Columns2': float,'columns':int})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Columns1  2 non-null      int32
 1   Column2   2 non-null      int64
 2   columns3  2 non-null      int64
 3   column4   1 non-null      float64
dtypes: float64(1), int32(1), int64(2)
memory usage: 184.0 bytes

In [75]:
data = ('MyIndex,Columns1,Column2,columns3,column4\n'
    '11,tony,100,4,p\n'
    '22,vednesday,200,6\n'
    '33,yuvraj,196,7,9')
pd.read_csv(StringIO(data),index_col = ['MyIndex'])

          Columns1  Column2  columns3 column4
MyIndex
11            tony      100         4       p
22       vednesday      200         6     NaN
33          yuvraj      196         7       9