In [56]:
import pandas as pd

In [57]:
html = pd.read_html("https://en.wikipedia.org/wiki/Economy_of_India")

In [58]:
type(html)

list

In [59]:
html

[                                                    0  \
 0         Mumbai, the financial centre of India[1][2]
 1                                            Currency
 2                                         Fiscal year
 3                                 Trade organisations
 4                                       Country group
 5                                          Statistics
 6                                          Population
 7                                                 GDP
 8                                            GDP rank
 9                                          GDP growth
 10                                     GDP per capita
 11                                GDP per capita rank
 12                                      GDP by sector
 13                                   GDP by component
 14                                    Inflation (CPI)
 15                                Base borrowing rate
 16                      Population below poverty line
 17                                   Gini coefficient
 18                            Human Development Index
 19                       Corruption Perceptions Index
 20                                       Labour force
 21                         Labour force by occupation
 22                                       Unemployment
 23                      Final consumption expenditure
 24                            Gross capital formation
 25                                      Gross savings
 26                                        Yield curve
 27                         Purchasing Managers' Index
 28                                    Main industries
 29                                           External
 30                                            Exports
 31                                       Export goods
 32                               Main export partners
 33                                            Imports
 34                                       Import goods
 35                               Main import partners
 36                                          FDI stock
 37                                    Current account
 38                                Gross external debt
 39              Net international investment position
 40                                    Public finances
 41                                    Government debt
 42                                     Budget balance
 43                                           Revenues
 44                                           Expenses
 45                                       Economic aid
 46                                      Credit rating
 47                                   Foreign reserves
 48  All values, unless otherwise stated, are in US...

                                                     1
 0         Mumbai, the financial centre of India[1][2]
 1                               Indian rupee (INR, ₹)
 2                                  1 April – 31 March
 3   WTO, WCO, SAFTA, BIMSTEC, WFTU, BRICS, G-20, B...
 4   Developing/Emerging[3] Lower-middle income eco...
 5                                          Statistics
 6                  1,428,627,663 (1st; 2024 est.)[11]
 7   $3.937 trillion (nominal; 2024 est.)[12]  $14....
 8                 5th (nominal; 2024) 3rd (PPP; 2024)
 9   8.2% (FY2024)[13]  7.2% (FY2023)[14]  9.7% (FY...
 10  $2,731 (nominal; 2024 est.)[13]  $10,123 (PPP;...
 11      136th (nominal; 2024)[a] 125th (PPP; 2024)[a]
 12  Agriculture: 18.4% Industry: 28.3% Services: 5...
 13  Private final consumption: 57.2% Government fi...
 14                             4.85% (March 2024)[18]
 15                      6.50% (9th February 2024)[19]
 16  82% on less than $6.85/day (2021)[20]  44% on ...
 17      35.7 medium (2019)[22] 32.8 medium (2021)[23]
 18  0.644 medium (2022, HDI 134th)[24]  0.444 low ...
 19        39 out of 100 points (2023)[25] (rank 93rd)
 20  586 million (2023)[26] 49.8% employment rate (...
 21  Agriculture: 42.60% [31] Industry: 25.12% [32]...
 22  7.6% March 2024 [34][35]  12.4% youth unemploy...
 23                            70.9% of GDP (2022)[37]
 24                              29% of GDP (2022)[38]
 25                          31.781% of GDP (2023)[39]
 26             10-year bond 7.190% (Jan 2023)[40][41]
 27  58.3 Manufacturing (June 2024)[42]  61.2 Servi...
 28  Textileschemicalsfood processingsteeltransport...
 29                                           External
 30                   $776.68 billion (FY 2023–24)[45]
 31  Manufacturers 70.7%Fuels and mining products 1...
 32  United States 17.7%  European Union 17.4%  Uni...
 33                   $854.80 billion (FY 2023–24)[45]
 34  Agricultural products 7%Fuels and mining produ...
 35  China 18.1%  Hong Kong 3.0%  Russia 9.1%  Euro...
 36                    $514 Billion (2021–22) [48][49]
 37  –$120.569 billion (2022)[39][50]  –3.476% of G...
 38    $663.8 billion (March 2024)[51] ( 18.7% of GDP)
 39                    –$379.7 billion (June 2023)[52]
 40                                    Public finances
 41  ₹246.531 trillion (US$3.0 trillion)[39]  81.9%...
 42                         –6.4% of GDP (2022–23)[53]
 43   ₹27.163 trillion (US$330 billion) (2023–24) [54]
 44   ₹45.031 trillion (US$540 billion) (2023–24) [54]
 45  Donor:  $4.234 billion (2021) ($30.59 billions...
 46  Standard & Poor's:[56] BBB− Outlook: Positive ...
 47  $653.71 billion[b][58] (4th) (as of 21 June 2024)
 48  All values, unless otherwise stated, are in US...  ,
     0                                                  1
 0 NaN  This article needs to be updated. Please help ...,
     Year  GDP (in Bil. US$PPP)  GDP per capita (in US$ PPP)  \
 0   1980                 371.9                        532.0
 1   1981                 431.5                        603.2
 2   1982                 474.1                        647.5
 3   1983                 528.6                        705.3
 4   1984                 568.6                        741.4
 5   1985                 617.4                        787.1
 6   1986                 659.9                        822.8
 7   1987                 703.0                        857.7
 8   1988                 797.9                        952.7
 9   1989                 878.5                       1027.0
 10  1990                 961.8                       1101.3
 11  1991                1004.8                       1127.4
 12  1992                1084.1                       1192.2
 13  1993                1162.5                       1253.5
 14  1994                1266.4                       1339.2
 15  1995                1390.8                       1442.9
 16  1996                1523.2                       1550.6
 17  1997                1612.3                       1610.8
 18  1998                1731.2                       1698.1
 19  1999                1904.2                       1834.4
 20  2000                2024.7                       1916.3
 21  2001                2172.7                       2021.1
 22  2002                2292.8                       2097.1
 23  2003                2523.8                       2270.6
 24  2004                2795.0                       2474.2
 25  2005                3150.3                       2745.1
 26  2006                3548.3                       3044.5
 27  2007                4001.4                       3381.8
 28  2008                4236.8                       3528.7
 29  2009                4625.5                       3798.5
 30  2010                5161.4                       4181.7
 31  2011                5618.4                       4493.7
 32  2012                6153.2                       4861.2
 33  2013                6477.5                       5057.2
 34  2014                6781.0                       5233.9
 35  2015                7159.8                       5464.9
 36  2016                7735.0                       5839.9
 37  2017                8276.9                       6112.1
 38  2018                9023.0                       6590.9
 39  2019                9540.4                       6897.8
 40  2020                9101.3                       6517.8
 41  2021               10370.8                       7355.4
 42  2022               11900.7                       8397.5
 43  2023               13119.6                       9183.4
 44  2024               14261.2                       9891.8
 45  2025               15469.1                      10634.6
 46  2026               16765.2                      11426.4
 47  2027               18155.7                      12270.8
 48  2028               19650.2                      13173.3

     GDP (in Bil. US$nominal)  GDP per capita (in US$ nominal)  \
 0                      189.4                            271.0
 1                      196.5                            274.7
 2                      203.5                            278.0
 3                      222.0                            296.3
 4                      215.6                            281.1
 5                      237.6                            302.9
 6                      252.8                            315.2
 7                      283.8                            346.2
 8                      299.6                            357.8
 9                      301.2                            352.2
 10                     326.6                            374.0
 11                     274.8                            308.4
 12                     293.3                            322.5
 13                     284.2                            306.4
 14                     333.0                            352.2
 15                     366.6                            380.3
 16                     399.8                            407.0
 17                     423.2                            422.8
 18                     428.8                            420.6
 19                     466.9                            449.8
 20                     476.6                            451.1
 21                     494.0                            459.5
 22                     524.0                            479.2
 23                     618.4                            556.3
 24                     721.6                            638.8
 25                     834.2                            726.9
 26                     949.1                            814.4
 27                    1238.7                           1046.9
 28                    1224.1                           1019.5
 29                    1365.4                           1121.2
 30                    1708.5                           1384.2
 31                    1823.1                           1458.1
 32                    1827.6                           1443.9
 33                    1856.7                           1449.6
 34                    2039.1                           1573.9
 35                    2103.6                           1605.6
 36                    2294.8                           1732.6
 37                    2702.9                           1958.0
 38                    2702.9                           1974.4
 39                    2835.6                           2050.2
 40                    2671.6                           1913.2
 41                    3150.3                           2234.3
 42                    3389.7                           2391.9
 43                    3732.2                           2612.5
 44                    4105.4                           2847.6
 45                    4511.8                           3101.8
 46                    4951.6                           3374.8
 47                    5427.4                           3668.2
 48                    5944.4                           3985.0

    GDP growth (real) Inflation rate (in Percent) Unemployment (in Percent)  \
 0              6.74%                       11.3%                       NaN
 1              6.01%                       12.7%                       NaN
 2               3.5%                        7.7%                       NaN
 3               7.3%                       12.6%                       NaN
 4               3.8%                        5.2%                       NaN
 5               5.3%                  5.56%[196]                       NaN
 6               4.8%                   7.8%[197]                       NaN
 7               4.0%                        9.1%                       NaN
 8             10.18%                        7.2%                       NaN
 9               5.9%                        4.6%                       NaN
 10              5.5%                       11.2%                       NaN
 11              1.1%                       13.5%                      6.8%
 12              5.5%                        9.9%                      6.8%
 13              4.8%                        7.3%                      6.8%
 14              6.7%                       10.3%                      6.8%
 15              7.6%                       10.0%                        7%
 16              7.6%                        9.4%                      7.2%
 17              4.1%                        6.8%                      7.3%
 18              6.2%                       13.1%                      7.5%
 19              8.5%                        5.7%                      7.7%
 20              4.0%                        3.8%                      7.8%
 21              4.9%                        4.3%                        8%
 22              3.9%                        4.0%                      8.2%
 23              7.9%                        3.9%                      8.4%
 24              7.8%                        3.8%                      8.5%
 25              9.3%                        4.4%                      8.7%
 26              9.3%                        6.7%                      8.6%
 27             10.3%                        6.2%                      8.5%
 28              3.9%                        9.1%                      8.5%
 29              7.9%                       12.3%                      8.4%
 30              8.5%                       10.5%                      8.3%
 31              6.6%                        9.5%                      8.2%
 32              5.5%                       10.0%                      8.1%
 33              6.4%                        9.4%                      8.1%
 34              7.4%                        5.8%                        8%
 35              8.0%                        4.9%                      7.9%
 36              8.3%                        4.5%                      7.8%
 37              6.8%                        3.6%                      7.7%
 38              6.5%                        3.4%                      7.7%
 39              4.2%                        4.8%                      6.5%
 40             -5.8%                        6.1%                      7.9%
 41         9.7%[198]                        5.5%                      6.4%
 42              7.2%                        6.7%                      4.8%
 43              8.2%                        5.5%                      4.7%
 44           7%[199]                        4.6%                       NaN
 45                7%                        4.1%                       NaN
 46                7%                        4.1%                       NaN
 47                7%                        4.0%                       NaN
 48                7%                        4.0%                       NaN

    Government debt (in % of GDP)
 0                            NaN
 1                            NaN
 2                            NaN
 3                            NaN
 4                            NaN
 5                            NaN
 6                            NaN
 7                            NaN
 8                            NaN
 9                            NaN
 10                           NaN
 11                         75.3%
 12                         77.4%
 13                         77.0%
 14                         73.5%
 15                         69.7%
 16                         66.0%
 17                         67.8%
 18                         68.1%
 19                         70.0%
 20                         73.6%
 21                         78.7%
 22                         82.9%
 23                         84.4%
 24                         83.4%
 25                         81.0%
 26                         77.2%
 27                         74.1%
 28                         72.8%
 29                         71.5%
 30                         66.4%
 31                         68.6%
 32                         68.0%
 33                         67.7%
 34                         67.1%
 35                         69.0%
 36                         68.9%
 37                         69.7%
 38                         70.4%
 39                         75.0%
 40                         88.5%
 41                         83.7%
 42                         81.0%
 43                         81.9%
 44                         82.3%
 45                         82.2%
 46                         81.8%
 47                         81.2%
 48                         80.5%  ,
     0                                                  1
 0 NaN  This article needs to be updated. Please help ...,
          Year  Exports (in USD billion)  Imports (in USD billion)  \
 0   2022[335]                    458.30                    725.40
 1        2021                    420.00                    612.00
 2        2020                    314.31                    467.19
 3        2019                    330.07                    514.07
 4        2018                    303.52                    465.58
 5        2017                    275.80                    384.30
 6        2016                    262.30                    381.00
 7        2015                    310.30                    447.90
 8        2014                    318.20                    462.90
 9        2013                    313.20                    467.50
 10       2012                    298.40                    500.40
 11       2011                    299.40                    461.40
 12       2010                    201.10                    327.00
 13       2009                    168.20                    274.30
 14       2008                    176.40                    305.50
 15       2007                    112.00                    100.90
 16       2006                     76.23                    113.10
 17       2005                     69.18                     89.33
 18       2004                     57.24                     74.15
 19       2003                     48.30                     61.60
 20       2002                     44.50                     53.80
 21       2001                     42.50                     54.50
 22       2000                     43.10                     60.80
 23       1999                     36.30                     50.20

     Trade Deficit (in USD billion)
 0                          -267.20
 1                          -192.00
 2                          -158.88
 3                          -184.00
 4                          -162.05
 5                          -108.50
 6                          -118.70
 7                          -137.60
 8                          -144.70
 9                          -154.30
 10                         -202.00
 11                         -162.00
 12                         -125.90
 13                         -106.10
 14                         -129.10
 15                           11.10
 16                          -36.87
 17                          -20.15
 18                          -16.91
 19                          -13.30
 20                           -9.30
 21                          -12.00
 22                          -17.70

In [60]:
html[0]

,0,1
0,"Mumbai, the financial centre of India[1][2]","Mumbai, the financial centre of India[1][2]"
1,Currency,"Indian rupee (INR, ₹)"
2,Fiscal year,1 April – 31 March
3,Trade organisations,"WTO, WCO, SAFTA, BIMSTEC, WFTU, BRICS, G-20, B..."
4,Country group,Developing/Emerging[3] Lower-middle income eco...
5,Statistics,Statistics
6,Population,"1,428,627,663 (1st; 2024 est.)[11]"
7,GDP,$3.937 trillion (nominal; 2024 est.)[12] $14....
8,GDP rank,5th (nominal; 2024) 3rd (PPP; 2024)
9,GDP growth,8.2% (FY2024)[13] 7.2% (FY2023)[14] 9.7% (FY...
10,GDP per capita,"$2,731 (nominal; 2024 est.)[13] $10,123 (PPP;..."
11,GDP per capita rank,136th (nominal; 2024)[a] 125th (PPP; 2024)[a]
12,GDP by sector,Agriculture: 18.4% Industry: 28.3% Services: 5...
13,GDP by component,Private final consumption: 57.2% Government fi...
14,Inflation (CPI),4.85% (March 2024)[18]
15,Base borrowing rate,6.50% (9th February 2024)[19]
16,Population below poverty line,82% on less than $6.85/day (2021)[20] 44% on ...
17,Gini coefficient,35.7 medium (2019)[22] 32.8 medium (2021)[23]
18,Human Development Index,"0.644 medium (2022, HDI 134th)[24] 0.444 low ..."
19,Corruption Perceptions Index,39 out of 100 points (2023)[25] (rank 93rd)
20,Labour force,586 million (2023)[26] 49.8% employment rate (...
21,Labour force by occupation,Agriculture: 42.60% [31] Industry: 25.12% [32]...
22,Unemployment,7.6% March 2024 [34][35] 12.4% youth unemploy...
23,Final consumption expenditure,70.9% of GDP (2022)[37]
24,Gross capital formation,29% of GDP (2022)[38]
25,Gross savings,31.781% of GDP (2023)[39]
26,Yield curve,10-year bond 7.190% (Jan 2023)[40][41]
27,Purchasing Managers' Index,58.3 Manufacturing (June 2024)[42] 61.2 Servi...
28,Main industries,Textileschemicalsfood processingsteeltransport...
29,External,External
30,Exports,$776.68 billion (FY 2023–24)[45]
31,Export goods,Manufacturers 70.7%Fuels and mining products 1...
32,Main export partners,United States 17.7% European Union 17.4% Uni...
33,Imports,$854.80 billion (FY 2023–24)[45]
34,Import goods,Agricultural products 7%Fuels and mining produ...
35,Main import partners,China 18.1% Hong Kong 3.0% Russia 9.1% Euro...
36,FDI stock,$514 Billion (2021–22) [48][49]
37,Current account,–$120.569 billion (2022)[39][50] –3.476% of G...
38,Gross external debt,$663.8 billion (March 2024)[51] ( 18.7% of GDP)
39,Net international investment position,–$379.7 billion (June 2023)[52]
40,Public finances,Public finances
41,Government debt,₹246.531 trillion (US$3.0 trillion)[39] 81.9%...
42,Budget balance,–6.4% of GDP (2022–23)[53]
43,Revenues,₹27.163 trillion (US$330 billion) (2023–24) [54]
44,Expenses,₹45.031 trillion (US$540 billion) (2023–24) [54]
45,Economic aid,Donor: $4.234 billion (2021) ($30.59 billions...
46,Credit rating,Standard & Poor's:[56] BBB− Outlook: Positive ...
47,Foreign reserves,$653.71 billion[b][58] (4th) (as of 21 June 2024)
48,"All values, unless otherwise stated, are in US...","All values, unless otherwise stated, are in US..."

In [61]:
html = pd.read_html("https://en.wikipedia.org/wiki/Economy_of_India",match = "Acquiror Nation")

In [62]:
html

[                                 0                            1  \
 0                    Acquiror Name        Acquiror Mid Industry
 1           Petrol Complex Pte Ltd                    Oil & Gas
 2                 Vodafone Grp Plc                     Wireless
 3   Vodafone Grp PLC-Vodafone Asts                     Wireless
 4                Bharti Airtel Ltd                     Wireless
 5                Bharti Airtel Ltd                     Wireless
 6                           BP PLC                    Oil & Gas
 7                    MTN Group Ltd                     Wireless
 8                     Shareholders             Other Financials
 9       Oil & Natural Gas Corp Ltd                    Oil & Gas
 10    Reliance Commun Ventures Ltd  Telecommunications Services

                   2                               3  \
 0   Acquiror Nation                     Target Name
 1         Singapore                   Essar Oil Ltd
 2    United Kingdom             Hutchison Essar Ltd
 3             India    Idea Cellular Ltd-Mobile Bus
 4             India                   MTN Group Ltd
 5             India                  Zain Africa BV
 6    United Kingdom  Reliance Industries Ltd-21 Oil
 7      South Africa               Bharti Airtel Ltd
 8             India   Reliance Inds Ltd-Telecom Bus
 9             India        Hindustan Petro Corp Ltd
 10            India           Reliance Infocomm Ltd

                               4              5                            6
 0           Target Mid Industry  Target Nation  Value of Transaction ($mil)
 1                     Oil & Gas          India                     12907.25
 2   Telecommunications Services          India                     12748.00
 3                      Wireless          India                     11627.32
 4                      Wireless   South Africa                     11387.52
 5                      Wireless        Nigeria                     10700.00
 6                     Oil & Gas          India                      9000.00
 7                      Wireless          India                      8775.09
 8   Telecommunications Services          India                      8063.01
 9                Petrochemicals          India                      5784.20
 10  Telecommunications Services          India                      5577.18  ]

In [63]:
html[0]

,0,1,2,3,4,5,6
0,Acquiror Name,Acquiror Mid Industry,Acquiror Nation,Target Name,Target Mid Industry,Target Nation,Value of Transaction ($mil)
1,Petrol Complex Pte Ltd,Oil & Gas,Singapore,Essar Oil Ltd,Oil & Gas,India,12907.25
2,Vodafone Grp Plc,Wireless,United Kingdom,Hutchison Essar Ltd,Telecommunications Services,India,12748.00
3,Vodafone Grp PLC-Vodafone Asts,Wireless,India,Idea Cellular Ltd-Mobile Bus,Wireless,India,11627.32
4,Bharti Airtel Ltd,Wireless,India,MTN Group Ltd,Wireless,South Africa,11387.52
5,Bharti Airtel Ltd,Wireless,India,Zain Africa BV,Wireless,Nigeria,10700.00
6,BP PLC,Oil & Gas,United Kingdom,Reliance Industries Ltd-21 Oil,Oil & Gas,India,9000.00
7,MTN Group Ltd,Wireless,South Africa,Bharti Airtel Ltd,Wireless,India,8775.09
8,Shareholders,Other Financials,India,Reliance Inds Ltd-Telecom Bus,Telecommunications Services,India,8063.01
9,Oil & Natural Gas Corp Ltd,Oil & Gas,India,Hindustan Petro Corp Ltd,Petrochemicals,India,5784.20
10,Reliance Commun Ventures Ltd,Telecommunications Services,India,Reliance Infocomm Ltd,Telecommunications Services,India,5577.18

In [64]:
html = pd.read_html("https://en.wikipedia.org/wiki/Economy_of_India")
A = html[2]

In [65]:
A.to_html('test.html')

In [66]:

df = pd.read_csv('test.csv')


df

,id,f0,f1,f2,f3,f4,f5,f6,f7,f8,...,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99
0,15000,0.398169,2.143300,114.8780,3.816510,0.089995,1.042540,5.307310,1.767470,1.350300,...,0.040523,1.308520,0.065694,0.047387,-0.035951,0.281766,0.477826,1.62488,0.029438,-0.031790
1,15001,0.008505,2.349320,853.8810,5.231130,0.049947,1.107780,0.928617,0.293212,1.117650,...,0.080400,4.083920,0.047871,0.105594,0.030981,0.096044,3.408660,2.27766,-0.015950,0.093279
2,15002,2.767680,2.084530,148.9250,4.046420,0.007924,4.261860,1.295550,-0.310799,4.306960,...,0.078513,-0.250609,0.029606,0.092942,-0.044077,0.106987,3.987810,1.68461,1.205700,0.106042
3,15003,1.071190,5.919520,-64.0648,0.195529,0.079169,0.903287,4.935910,1.769730,1.766360,...,0.103638,0.938042,0.014003,0.050670,0.114732,0.405016,3.223190,4.58780,0.051759,0.094247
4,15004,0.068140,3.539450,-25.8223,5.739260,0.038304,3.349190,4.220190,1.177650,4.929340,...,0.106432,3.928190,0.700506,0.013716,0.033387,0.057754,3.433780,3.64833,0.076186,0.045207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,24995,-0.005145,3.001410,210.6070,0.994924,0.019112,2.783550,3.405270,1.108160,3.612990,...,0.017866,0.564076,0.041830,0.067117,0.095220,0.493235,2.321530,1.70168,1.191190,-0.013795
9996,24996,0.119577,4.266310,162.3760,1.245620,0.026891,1.119720,2.455950,1.892510,1.884320,...,0.038461,2.750980,0.095389,0.115835,-0.001519,0.329741,1.553460,4.93422,0.098288,0.059588
9997,24997,-0.074183,0.268787,199.6410,5.217750,-0.036501,3.469370,3.917630,3.325400,2.533160,...,0.093584,1.020830,0.017167,0.099463,0.097122,0.275216,0.421355,1.31525,0.168879,0.004827
9998,24998,-0.049194,4.064200,3400.6200,3.039560,0.089791,1.248200,1.868640,3.843320,-0.492011,...,0.049420,4.830970,0.128419,0.053590,0.044978,0.269863,4.731870,2.31149,0.082613,0.108157
9999,24999,0.024247,1.525240,140.1220,1.444970,0.110097,0.614881,4.020260,1.172260,-0.323853,...,-0.013819,5.423580,0.011909,0.113500,1.541270,0.085786,1.624360,2.99767,0.631893,-0.004036

In [70]:
A = df.iloc[:6,:7]

In [71]:
A.to_html('test2.html')