### Fake new Classification : -

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/WELFake_Dataset.csv")
print(df.shape)
df.head()

(72134, 4)

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [4]:
df = df[["title","text","label"]]
df.sample(10)

,title,text,label
43405,Iran Nuclear Talks Go To The Wire With 50-50 C...,Negotiators have been hesitant to publicly sha...,0
41573,ICE Agent Commits Suicide in NYC; Leaves Note ...,Email Print After writing a lengthy suicide no...,1
47832,"Turkey to hire 110,000 new public servants in ...",ISTANBUL (Reuters) - Turkey s Prime Minister B...,0
43609,American Airlines Throws Ivy League Economist...,Ivy League economist Guido Menzio has reported...,1
42454,World leaders' personal chefs sample Indian ma...,World leaders' personal chefs sample Indian ma...,1
49574,Microsoft Just Gamed Our Tax System With Its ...,Microsoft is buying LinkedIn and they have so ...,1
31965,CLASS ACT: Trump Finds Out NY Man’s TRUMP Sign...,Donald Trump has done so many things that you ...,1
4898,Redstone’s Lawyers Argue That His Mental Healt...,In an unexpected twist in an already tumultuou...,0
67475,Japan's Abe calls for enforcement of sanctions...,TOKYO (Reuters) - The international community ...,0
56731,BREAKING NEWS: DACA IS DONE! WATCH AG Jeff Ses...,President Trump keeps another promise. The win...,1

In [6]:
df.shape

(72134, 3)

In [5]:
df.isnull().sum()

title    558
text      39
label      0
dtype: int64

In [9]:
df1 = df.dropna(subset=['title','text'])
df1.isnull().sum()

title    0
text     0
label    0
dtype: int64

In [11]:
print(df1.shape)
df1.sample(6)

(71537, 3)

,title,text,label
40155,Clinton’s Potential Attorney Gen Pick Mocks Mi...,Share on Twitter \nU.S. Secretary of Labor Tom...,1
53554,Fox News Gets Destroyed While Trying To Blame ...,"By Jason Easley on Sun, Oct 30th, 2016 at 2:37...",1
1827,Republican’s Excuse For Cutting Food Stamps: ...,Republican lawmakers love using the Bible to d...,1
36564,Kremlin says U.S. closure of consulate fuels U...,MOSCOW (Reuters) - The Kremlin said on Friday ...,0
41718,This Liberal Group Found The BEST Way To Ruin...,The Republican National Convention was already...,1
17317,Trump’s Latest Tease Pales Next to Bush and Go...,It s teetering on the ridiculous watching the...,1

In [12]:
df.label.value_counts()

label
1    37106
0    35028
Name: count, dtype: int64

In [ ]:
df['title'].iloc[0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [18]:
df['text'].iloc[0]

'No comment is expected from Barack Obama Members of the #FYF911 or #FukYoFlag and #BlackLivesMatter movements called for the lynching and hanging of white people and cops. They encouraged others on a radio show Tuesday night to  turn the tide  and kill white people and cops to send a message about the killing of black people in America.One of the F***YoFlag organizers is called  Sunshine.  She has a radio blog show hosted from Texas called,  Sunshine s F***ing Opinion Radio Show. A snapshot of her #FYF911 @LOLatWhiteFear Twitter page at 9:53 p.m. shows that she was urging supporters to  Call now!! #fyf911 tonight we continue to dismantle the illusion of white Below is a SNAPSHOT Twitter Radio Call Invite   #FYF911The radio show aired at 10:00 p.m. eastern standard time.During the show, callers clearly call for  lynching  and  killing  of white people.A 2:39 minute clip from the radio show can be heard here. It was provided to Breitbart Texas by someone who would like to be referred to as  Hannibal.  He has already received death threats as a result of interrupting #FYF911 conference calls.An unidentified black man said  when those mother f**kers are by themselves, that s when when we should start f***ing them up. Like they do us, when a bunch of them ni**ers takin  one of us out, that s how we should roll up.  He said,  Cause we already roll up in gangs anyway. There should be six or seven black mother f**ckers, see that white person, and then lynch their ass. Let s turn the tables. They conspired that if  cops started losing people,  then  there will be a state of emergency. He speculated that one of two things would happen,  a big-ass [R s?????] war,  or  ni**ers, they are going to start backin  up. We are already getting killed out here so what the f**k we got to lose? Sunshine could be heard saying,  Yep, that s true. That s so f**king true. He said,  We need to turn the tables on them. Our kids are getting shot out here. Somebody needs to become a sacrifice on their side.He said,  Everybody ain t down for that s**t, or whatever, but like I say, everybody has a different position of war.  He continued,  Because they don t give a f**k anyway.  He said again,  We might as well utilized them for that s**t and turn the tables on these n**ers. He said, that way  we can start lookin  like we ain t havin  that many casualties, and there can be more causalities on their side instead of ours. They are out their killing black people, black lives don t matter, that s what those mother f**kers   so we got to make it matter to them. Find a mother f**ker that is alone. Snap his ass, and then f***in hang him from a damn tree. Take a picture of it and then send it to the mother f**kers. We  just need one example,  and  then people will start watchin .  This will turn the tables on s**t, he said. He said this will start  a trickle-down effect.  He said that when one white person is hung and then they are just  flat-hanging,  that will start the  trickle-down effect.  He continued,  Black people are good at starting trends. He said that was how  to get the upper-hand. Another black man spoke up saying they needed to kill  cops that are killing us. The first black male said,  That will be the best method right there. Breitbart Texas previously reported how Sunshine was upset when  racist white people  infiltrated and disrupted one of her conference calls. She subsequently released the phone number of one of the infiltrators. The veteran immediately started receiving threatening calls.One of the #F***YoFlag movement supporters allegedly told a veteran who infiltrated their publicly posted conference call,  We are going to rape and gut your pregnant wife, and your f***ing piece of sh*t unborn creature will be hung from a tree. Breitbart Texas previously encountered Sunshine at a Sandra Bland protest at the Waller County Jail in Texas, where she said all white people should be killed. She told journalists and photographers,  You see this nappy-ass hair on my head?   That means I am one of those more militant Negroes.  She said she was at the protest because  these redneck mother-f**kers murdered Sandra Bland because she had nappy hair like me. #FYF911 black radicals say they will be holding the  imperial powers  that are actually responsible for the terrorist attacks on September 11th accountable on that day, as reported by Breitbart Texas. There are several websites and Twitter handles for the movement. Palmetto Star  describes himself as one of the head organizers. He said in a YouTube video that supporters will be burning their symbols of  the illusion of their superiority,  their  false white supremacy,  like the American flag, the British flag, police uniforms, and Ku Klux Klan hoods.Sierra McGrone or  Nocturnus Libertus  posted,  you too can help a young Afrikan clean their a** with the rag of oppression.  She posted two photos, one that appears to be herself, and a photo of a black man, wiping their naked butts with the American flag.For entire story: Breitbart News'

### Preprocessing : -

In [22]:
import re

def clean_text(text):

    text = str(text).lower()   # convert to string first
    
    text = re.sub(r'@\w+', '', text)        # remove mentions
    text = re.sub(r'#\w+', '', text)        # remove hashtags
    text = re.sub(r'\b\d{1,2}:\d{2}(\s?[ap]\.?m\.?)?', '', text)  # remove time
    text = re.sub(r'\d+', '', text)         # remove numbers
    text = re.sub(r'[^\w\s]', '', text)     # remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [25]:
df1['new_title'] = df1['title'].apply(clean_text)
df1.head()

/var/folders/rr/d0gz2wj51xg3h4b_s1cxz0bc0000gn/T/ipykernel_68328/1751697549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['new_title'] = df1['title'].apply(clean_text)

,title,text,label,new_title
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,law enforcement on high alert following threat...
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,unbelievable obamas attorney general says most...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,bobby jindal raised hindu uses story of christ...
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,satan russia unvelis an image of its terrifyin...
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1,about time christian group sues amazon and spl...